/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl.tables.records;


import javax.annotation.Generated;

import org.citi.model.ddl.tables.Auditsteps;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditstepsRecord extends UpdatableRecordImpl<AuditstepsRecord> implements Record14<Long, String, String, String, String, String, String, String, String, String, String, String, String, Long> {

    private static final long serialVersionUID = 1209273769;

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.ACTIVITYNAME</code>.
     */
    public void setActivityname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.ACTIVITYNAME</code>.
     */
    public String getActivityname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.DURATION</code>.
     */
    public void setDuration(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.DURATION</code>.
     */
    public String getDuration() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.ERRORMSG</code>.
     */
    public void setErrormsg(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.ERRORMSG</code>.
     */
    public String getErrormsg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.ERRORSEVERITY</code>.
     */
    public void setErrorseverity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.ERRORSEVERITY</code>.
     */
    public String getErrorseverity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.ERRORTYPE</code>.
     */
    public void setErrortype(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.ERRORTYPE</code>.
     */
    public String getErrortype() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.LOGID</code>.
     */
    public void setLogid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.LOGID</code>.
     */
    public String getLogid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.LOGLEVEL</code>.
     */
    public void setLoglevel(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.LOGLEVEL</code>.
     */
    public String getLoglevel() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.LOGTIMESTAMP</code>.
     */
    public void setLogtimestamp(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.LOGTIMESTAMP</code>.
     */
    public String getLogtimestamp() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.MESSAGE</code>.
     */
    public void setMessage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.MESSAGE</code>.
     */
    public String getMessage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.SERVICEPROVIDER</code>.
     */
    public void setServiceprovider(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.SERVICEPROVIDER</code>.
     */
    public String getServiceprovider() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.TRACKINGID</code>.
     */
    public void setTrackingid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.TRACKINGID</code>.
     */
    public String getTrackingid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.UUID</code>.
     */
    public void setUuid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.UUID</code>.
     */
    public String getUuid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.AUDITSTEPS.EAGLEAUDITS_ID</code>.
     */
    public void setEagleauditsId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.AUDITSTEPS.EAGLEAUDITS_ID</code>.
     */
    public Long getEagleauditsId() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, String, String, String, Long> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, String, String, String, Long> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Auditsteps.AUDITSTEPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Auditsteps.AUDITSTEPS.ACTIVITYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Auditsteps.AUDITSTEPS.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Auditsteps.AUDITSTEPS.ERRORMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Auditsteps.AUDITSTEPS.ERRORSEVERITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Auditsteps.AUDITSTEPS.ERRORTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Auditsteps.AUDITSTEPS.LOGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Auditsteps.AUDITSTEPS.LOGLEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Auditsteps.AUDITSTEPS.LOGTIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Auditsteps.AUDITSTEPS.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Auditsteps.AUDITSTEPS.SERVICEPROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Auditsteps.AUDITSTEPS.TRACKINGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Auditsteps.AUDITSTEPS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Auditsteps.AUDITSTEPS.EAGLEAUDITS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getActivityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getErrormsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getErrorseverity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getErrortype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLogid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLoglevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLogtimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getServiceprovider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTrackingid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component14() {
        return getEagleauditsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getActivityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getErrormsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getErrorseverity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getErrortype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLogid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLoglevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLogtimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getServiceprovider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTrackingid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getEagleauditsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value2(String value) {
        setActivityname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value3(String value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value4(String value) {
        setErrormsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value5(String value) {
        setErrorseverity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value6(String value) {
        setErrortype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value7(String value) {
        setLogid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value8(String value) {
        setLoglevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value9(String value) {
        setLogtimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value10(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value11(String value) {
        setServiceprovider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value12(String value) {
        setTrackingid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value13(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord value14(Long value) {
        setEagleauditsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditstepsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Long value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditstepsRecord
     */
    public AuditstepsRecord() {
        super(Auditsteps.AUDITSTEPS);
    }

    /**
     * Create a detached, initialised AuditstepsRecord
     */
    public AuditstepsRecord(Long id, String activityname, String duration, String errormsg, String errorseverity, String errortype, String logid, String loglevel, String logtimestamp, String message, String serviceprovider, String trackingid, String uuid, Long eagleauditsId) {
        super(Auditsteps.AUDITSTEPS);

        set(0, id);
        set(1, activityname);
        set(2, duration);
        set(3, errormsg);
        set(4, errorseverity);
        set(5, errortype);
        set(6, logid);
        set(7, loglevel);
        set(8, logtimestamp);
        set(9, message);
        set(10, serviceprovider);
        set(11, trackingid);
        set(12, uuid);
        set(13, eagleauditsId);
    }
}
