/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl.tables.records;


import javax.annotation.Generated;

import org.citi.model.ddl.tables.Eagleaudits;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EagleauditsRecord extends UpdatableRecordImpl<EagleauditsRecord> {

    private static final long serialVersionUID = -1945781172;

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ACTIVITYNAME</code>.
     */
    public void setActivityname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ACTIVITYNAME</code>.
     */
    public String getActivityname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ADDITIONALINFO</code>.
     */
    public void setAdditionalinfo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ADDITIONALINFO</code>.
     */
    public String getAdditionalinfo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.BUSINESSREFID</code>.
     */
    public void setBusinessrefid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.BUSINESSREFID</code>.
     */
    public String getBusinessrefid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.CSIAPPID</code>.
     */
    public void setCsiappid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.CSIAPPID</code>.
     */
    public String getCsiappid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.CSIAPPNAME</code>.
     */
    public void setCsiappname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.CSIAPPNAME</code>.
     */
    public String getCsiappname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.DURATION</code>.
     */
    public void setDuration(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.DURATION</code>.
     */
    public String getDuration() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.EAGLEAPPNAME</code>.
     */
    public void setEagleappname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.EAGLEAPPNAME</code>.
     */
    public String getEagleappname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.EAGLEAPPID</code>.
     */
    public void setEagleappid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.EAGLEAPPID</code>.
     */
    public String getEagleappid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ENGINENAME</code>.
     */
    public void setEnginename(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ENGINENAME</code>.
     */
    public String getEnginename() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ERRORMSG</code>.
     */
    public void setErrormsg(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ERRORMSG</code>.
     */
    public String getErrormsg() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ERRORSEVERITY</code>.
     */
    public void setErrorseverity(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ERRORSEVERITY</code>.
     */
    public String getErrorseverity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ERRORTYPE</code>.
     */
    public void setErrortype(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ERRORTYPE</code>.
     */
    public String getErrortype() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.HOSTNAME</code>.
     */
    public void setHostname(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.HOSTNAME</code>.
     */
    public String getHostname() {
        return (String) get(13);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.IPADDRESS</code>.
     */
    public void setIpaddress(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.IPADDRESS</code>.
     */
    public String getIpaddress() {
        return (String) get(14);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.LASTUPDATETIME</code>.
     */
    public void setLastupdatetime(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.LASTUPDATETIME</code>.
     */
    public String getLastupdatetime() {
        return (String) get(15);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.LIBRARYVERSION</code>.
     */
    public void setLibraryversion(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.LIBRARYVERSION</code>.
     */
    public String getLibraryversion() {
        return (String) get(16);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.LOGID</code>.
     */
    public void setLogid(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.LOGID</code>.
     */
    public String getLogid() {
        return (String) get(17);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.LOGLEVEL</code>.
     */
    public void setLoglevel(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.LOGLEVEL</code>.
     */
    public String getLoglevel() {
        return (String) get(18);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.LOGTIMESTAMP</code>.
     */
    public void setLogtimestamp(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.LOGTIMESTAMP</code>.
     */
    public String getLogtimestamp() {
        return (String) get(19);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.MESSAGE</code>.
     */
    public void setMessage(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.MESSAGE</code>.
     */
    public String getMessage() {
        return (String) get(20);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.OPERATION</code>.
     */
    public void setOperation(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.OPERATION</code>.
     */
    public String getOperation() {
        return (String) get(21);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.ORIGAPP</code>.
     */
    public void setOrigapp(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.ORIGAPP</code>.
     */
    public String getOrigapp() {
        return (String) get(22);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SRCAPPNAME</code>.
     */
    public void setSrcappname(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SRCAPPNAME</code>.
     */
    public String getSrcappname() {
        return (String) get(23);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SRCCOUNTRYCODE</code>.
     */
    public void setSrccountrycode(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SRCCOUNTRYCODE</code>.
     */
    public String getSrccountrycode() {
        return (String) get(24);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SRCOPERATION</code>.
     */
    public void setSrcoperation(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SRCOPERATION</code>.
     */
    public String getSrcoperation() {
        return (String) get(25);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SRCSERVICE</code>.
     */
    public void setSrcservice(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SRCSERVICE</code>.
     */
    public String getSrcservice() {
        return (String) get(26);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SRCSERVICEVERSION</code>.
     */
    public void setSrcserviceversion(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SRCSERVICEVERSION</code>.
     */
    public String getSrcserviceversion() {
        return (String) get(27);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SRCUSER</code>.
     */
    public void setSrcuser(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SRCUSER</code>.
     */
    public String getSrcuser() {
        return (String) get(28);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SERVICE</code>.
     */
    public void setService(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SERVICE</code>.
     */
    public String getService() {
        return (String) get(29);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SERVICEPROVIDER</code>.
     */
    public void setServiceprovider(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SERVICEPROVIDER</code>.
     */
    public String getServiceprovider() {
        return (String) get(30);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.SERVICEVERSION</code>.
     */
    public void setServiceversion(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.SERVICEVERSION</code>.
     */
    public String getServiceversion() {
        return (String) get(31);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.TOTALPROCESSINGTIME</code>.
     */
    public void setTotalprocessingtime(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.TOTALPROCESSINGTIME</code>.
     */
    public String getTotalprocessingtime() {
        return (String) get(32);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.TRACKINGID</code>.
     */
    public void setTrackingid(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.TRACKINGID</code>.
     */
    public String getTrackingid() {
        return (String) get(33);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.TRANSACTIONSTATUS</code>.
     */
    public void setTransactionstatus(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.TRANSACTIONSTATUS</code>.
     */
    public String getTransactionstatus() {
        return (String) get(34);
    }

    /**
     * Setter for <code>PUBLIC.EAGLEAUDITS.UUID</code>.
     */
    public void setUuid(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>PUBLIC.EAGLEAUDITS.UUID</code>.
     */
    public String getUuid() {
        return (String) get(35);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EagleauditsRecord
     */
    public EagleauditsRecord() {
        super(Eagleaudits.EAGLEAUDITS);
    }

    /**
     * Create a detached, initialised EagleauditsRecord
     */
    public EagleauditsRecord(Long id, String activityname, String additionalinfo, String businessrefid, String csiappid, String csiappname, String duration, String eagleappname, String eagleappid, String enginename, String errormsg, String errorseverity, String errortype, String hostname, String ipaddress, String lastupdatetime, String libraryversion, String logid, String loglevel, String logtimestamp, String message, String operation, String origapp, String srcappname, String srccountrycode, String srcoperation, String srcservice, String srcserviceversion, String srcuser, String service, String serviceprovider, String serviceversion, String totalprocessingtime, String trackingid, String transactionstatus, String uuid) {
        super(Eagleaudits.EAGLEAUDITS);

        set(0, id);
        set(1, activityname);
        set(2, additionalinfo);
        set(3, businessrefid);
        set(4, csiappid);
        set(5, csiappname);
        set(6, duration);
        set(7, eagleappname);
        set(8, eagleappid);
        set(9, enginename);
        set(10, errormsg);
        set(11, errorseverity);
        set(12, errortype);
        set(13, hostname);
        set(14, ipaddress);
        set(15, lastupdatetime);
        set(16, libraryversion);
        set(17, logid);
        set(18, loglevel);
        set(19, logtimestamp);
        set(20, message);
        set(21, operation);
        set(22, origapp);
        set(23, srcappname);
        set(24, srccountrycode);
        set(25, srcoperation);
        set(26, srcservice);
        set(27, srcserviceversion);
        set(28, srcuser);
        set(29, service);
        set(30, serviceprovider);
        set(31, serviceversion);
        set(32, totalprocessingtime);
        set(33, trackingid);
        set(34, transactionstatus);
        set(35, uuid);
    }
}
