/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl.tables.records;


import javax.annotation.Generated;

import org.citi.model.ddl.tables.Numtx;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NumtxRecord extends UpdatableRecordImpl<NumtxRecord> implements Record6<Long, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = 2070462042;

    /**
     * Setter for <code>PUBLIC.NUMTX.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.NUMTX.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.NUMTX.FROMTIME</code>.
     */
    public void setFromtime(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.NUMTX.FROMTIME</code>.
     */
    public String getFromtime() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.NUMTX.NUMERR</code>.
     */
    public void setNumerr(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.NUMTX.NUMERR</code>.
     */
    public Integer getNumerr() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.NUMTX.NUMTX</code>.
     */
    public void setNumtx(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.NUMTX.NUMTX</code>.
     */
    public Integer getNumtx() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.NUMTX.OPERATIONNAME</code>.
     */
    public void setOperationname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.NUMTX.OPERATIONNAME</code>.
     */
    public String getOperationname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.NUMTX.TOTIME</code>.
     */
    public void setTotime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.NUMTX.TOTIME</code>.
     */
    public String getTotime() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Integer, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Integer, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Numtx.NUMTX.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Numtx.NUMTX.FROMTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Numtx.NUMTX.NUMERR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Numtx.NUMTX.NUMTX_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Numtx.NUMTX.OPERATIONNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Numtx.NUMTX.TOTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFromtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getNumerr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getNumtx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOperationname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTotime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFromtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNumerr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNumtx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOperationname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTotime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord value2(String value) {
        setFromtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord value3(Integer value) {
        setNumerr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord value4(Integer value) {
        setNumtx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord value5(String value) {
        setOperationname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord value6(String value) {
        setTotime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumtxRecord values(Long value1, String value2, Integer value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NumtxRecord
     */
    public NumtxRecord() {
        super(Numtx.NUMTX);
    }

    /**
     * Create a detached, initialised NumtxRecord
     */
    public NumtxRecord(Long id, String fromtime, Integer numerr, Integer numtx, String operationname, String totime) {
        super(Numtx.NUMTX);

        set(0, id);
        set(1, fromtime);
        set(2, numerr);
        set(3, numtx);
        set(4, operationname);
        set(5, totime);
    }
}
