/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl;


import gon.cue.model.ddl.tables.MegaConfigurations;
import gon.cue.model.ddl.tables.MegaUser;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SYS_IDX_SYS_PK_10092_10094 = Indexes0.SYS_IDX_SYS_PK_10092_10094;
    public static final Index SYS_IDX_10107 = Indexes0.SYS_IDX_10107;
    public static final Index SYS_IDX_SYS_PK_10098_10102 = Indexes0.SYS_IDX_SYS_PK_10098_10102;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index SYS_IDX_SYS_PK_10092_10094 = createIndex("SYS_IDX_SYS_PK_10092_10094", MegaConfigurations.MEGA_CONFIGURATIONS, new OrderField[] { MegaConfigurations.MEGA_CONFIGURATIONS.ID }, true);
        public static Index SYS_IDX_10107 = createIndex("SYS_IDX_10107", MegaUser.MEGA_USER, new OrderField[] { MegaUser.MEGA_USER.ID_CONFIG }, false);
        public static Index SYS_IDX_SYS_PK_10098_10102 = createIndex("SYS_IDX_SYS_PK_10098_10102", MegaUser.MEGA_USER, new OrderField[] { MegaUser.MEGA_USER.ID }, true);
    }
}
