/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl;


import gon.cue.model.ddl.tables.MegaConfigurations;
import gon.cue.model.ddl.tables.MegaUser;
import gon.cue.model.ddl.tables.records.MegaConfigurationsRecord;
import gon.cue.model.ddl.tables.records.MegaUserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MegaConfigurationsRecord, Integer> IDENTITY_MEGA_CONFIGURATIONS = Identities0.IDENTITY_MEGA_CONFIGURATIONS;
    public static final Identity<MegaUserRecord, Integer> IDENTITY_MEGA_USER = Identities0.IDENTITY_MEGA_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MegaConfigurationsRecord> SYS_PK_10092 = UniqueKeys0.SYS_PK_10092;
    public static final UniqueKey<MegaUserRecord> SYS_PK_10098 = UniqueKeys0.SYS_PK_10098;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MegaUserRecord, MegaConfigurationsRecord> MEGA_USER_MEGA_CONFIGURATIONS_FK = ForeignKeys0.MEGA_USER_MEGA_CONFIGURATIONS_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<MegaConfigurationsRecord, Integer> IDENTITY_MEGA_CONFIGURATIONS = createIdentity(MegaConfigurations.MEGA_CONFIGURATIONS, MegaConfigurations.MEGA_CONFIGURATIONS.ID);
        public static Identity<MegaUserRecord, Integer> IDENTITY_MEGA_USER = createIdentity(MegaUser.MEGA_USER, MegaUser.MEGA_USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MegaConfigurationsRecord> SYS_PK_10092 = createUniqueKey(MegaConfigurations.MEGA_CONFIGURATIONS, "SYS_PK_10092", MegaConfigurations.MEGA_CONFIGURATIONS.ID);
        public static final UniqueKey<MegaUserRecord> SYS_PK_10098 = createUniqueKey(MegaUser.MEGA_USER, "SYS_PK_10098", MegaUser.MEGA_USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<MegaUserRecord, MegaConfigurationsRecord> MEGA_USER_MEGA_CONFIGURATIONS_FK = createForeignKey(gon.cue.model.ddl.Keys.SYS_PK_10092, MegaUser.MEGA_USER, "MEGA_USER_MEGA_CONFIGURATIONS_FK", MegaUser.MEGA_USER.ID_CONFIG);
    }
}
