/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl;


import gon.cue.model.ddl.tables.MegaConfigurations;
import gon.cue.model.ddl.tables.MegaUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.MEGA_CONFIGURATIONS</code>.
     */
    public static final MegaConfigurations MEGA_CONFIGURATIONS = gon.cue.model.ddl.tables.MegaConfigurations.MEGA_CONFIGURATIONS;

    /**
     * The table <code>PUBLIC.MEGA_USER</code>.
     */
    public static final MegaUser MEGA_USER = gon.cue.model.ddl.tables.MegaUser.MEGA_USER;
}
