/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables.records;


import gon.cue.model.ddl.tables.MegaConfigurations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MegaConfigurationsRecord extends UpdatableRecordImpl<MegaConfigurationsRecord> implements Record2<Integer, Boolean> {

    private static final long serialVersionUID = -1549145230;

    /**
     * Setter for <code>PUBLIC.MEGA_CONFIGURATIONS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MEGA_CONFIGURATIONS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MEGA_CONFIGURATIONS.APP_MODE</code>.
     */
    public void setAppMode(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MEGA_CONFIGURATIONS.APP_MODE</code>.
     */
    public Boolean getAppMode() {
        return (Boolean) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Boolean> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Boolean> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MegaConfigurations.MEGA_CONFIGURATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return MegaConfigurations.MEGA_CONFIGURATIONS.APP_MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getAppMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getAppMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaConfigurationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaConfigurationsRecord value2(Boolean value) {
        setAppMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaConfigurationsRecord values(Integer value1, Boolean value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MegaConfigurationsRecord
     */
    public MegaConfigurationsRecord() {
        super(MegaConfigurations.MEGA_CONFIGURATIONS);
    }

    /**
     * Create a detached, initialised MegaConfigurationsRecord
     */
    public MegaConfigurationsRecord(Integer id, Boolean appMode) {
        super(MegaConfigurations.MEGA_CONFIGURATIONS);

        set(0, id);
        set(1, appMode);
    }
}
