/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables.records;


import gon.cue.model.ddl.tables.MegaUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MegaUserRecord extends UpdatableRecordImpl<MegaUserRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1971529382;

    /**
     * Setter for <code>PUBLIC.MEGA_USER.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MEGA_USER.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MEGA_USER.USER_NAME</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MEGA_USER.USER_NAME</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.MEGA_USER.USER_PASSWORD</code>.
     */
    public void setUserPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.MEGA_USER.USER_PASSWORD</code>.
     */
    public String getUserPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.MEGA_USER.ID_CONFIG</code>.
     */
    public void setIdConfig(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.MEGA_USER.ID_CONFIG</code>.
     */
    public Integer getIdConfig() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MegaUser.MEGA_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MegaUser.MEGA_USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MegaUser.MEGA_USER.USER_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MegaUser.MEGA_USER.ID_CONFIG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIdConfig();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdConfig();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaUserRecord value3(String value) {
        setUserPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaUserRecord value4(Integer value) {
        setIdConfig(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaUserRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MegaUserRecord
     */
    public MegaUserRecord() {
        super(MegaUser.MEGA_USER);
    }

    /**
     * Create a detached, initialised MegaUserRecord
     */
    public MegaUserRecord(Integer id, String userName, String userPassword, Integer idConfig) {
        super(MegaUser.MEGA_USER);

        set(0, id);
        set(1, userName);
        set(2, userPassword);
        set(3, idConfig);
    }
}
