/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables;


import gon.cue.model.ddl.Indexes;
import gon.cue.model.ddl.Keys;
import gon.cue.model.ddl.Public;
import gon.cue.model.ddl.tables.records.MegaConfigurationsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MegaConfigurations extends TableImpl<MegaConfigurationsRecord> {

    private static final long serialVersionUID = 1544086970;

    /**
     * The reference instance of <code>PUBLIC.MEGA_CONFIGURATIONS</code>
     */
    public static final MegaConfigurations MEGA_CONFIGURATIONS = new MegaConfigurations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MegaConfigurationsRecord> getRecordType() {
        return MegaConfigurationsRecord.class;
    }

    /**
     * The column <code>PUBLIC.MEGA_CONFIGURATIONS.ID</code>.
     */
    public final TableField<MegaConfigurationsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.MEGA_CONFIGURATIONS.APP_MODE</code>.
     */
    public final TableField<MegaConfigurationsRecord, Boolean> APP_MODE = createField("APP_MODE", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.MEGA_CONFIGURATIONS</code> table reference
     */
    public MegaConfigurations() {
        this(DSL.name("MEGA_CONFIGURATIONS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.MEGA_CONFIGURATIONS</code> table reference
     */
    public MegaConfigurations(String alias) {
        this(DSL.name(alias), MEGA_CONFIGURATIONS);
    }

    /**
     * Create an aliased <code>PUBLIC.MEGA_CONFIGURATIONS</code> table reference
     */
    public MegaConfigurations(Name alias) {
        this(alias, MEGA_CONFIGURATIONS);
    }

    private MegaConfigurations(Name alias, Table<MegaConfigurationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MegaConfigurations(Name alias, Table<MegaConfigurationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_IDX_SYS_PK_10092_10094);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MegaConfigurationsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MEGA_CONFIGURATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MegaConfigurationsRecord> getPrimaryKey() {
        return Keys.SYS_PK_10092;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MegaConfigurationsRecord>> getKeys() {
        return Arrays.<UniqueKey<MegaConfigurationsRecord>>asList(Keys.SYS_PK_10092);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaConfigurations as(String alias) {
        return new MegaConfigurations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegaConfigurations as(Name alias) {
        return new MegaConfigurations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MegaConfigurations rename(String name) {
        return new MegaConfigurations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MegaConfigurations rename(Name name) {
        return new MegaConfigurations(name, null);
    }
}
