/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.citi.model.ddl.Indexes;
import org.citi.model.ddl.Keys;
import org.citi.model.ddl.Public;
import org.citi.model.ddl.tables.records.AuditstepsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auditsteps extends TableImpl<AuditstepsRecord> {

    private static final long serialVersionUID = -14193607;

    /**
     * The reference instance of <code>PUBLIC.AUDITSTEPS</code>
     */
    public static final Auditsteps AUDITSTEPS = new Auditsteps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditstepsRecord> getRecordType() {
        return AuditstepsRecord.class;
    }

    /**
     * The column <code>PUBLIC.AUDITSTEPS.ID</code>.
     */
    public final TableField<AuditstepsRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_205A61F8_CFCE_4731_82B5_D948F6362318)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.ACTIVITYNAME</code>.
     */
    public final TableField<AuditstepsRecord, String> ACTIVITYNAME = createField("ACTIVITYNAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.DURATION</code>.
     */
    public final TableField<AuditstepsRecord, String> DURATION = createField("DURATION", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.ERRORMSG</code>.
     */
    public final TableField<AuditstepsRecord, String> ERRORMSG = createField("ERRORMSG", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.ERRORSEVERITY</code>.
     */
    public final TableField<AuditstepsRecord, String> ERRORSEVERITY = createField("ERRORSEVERITY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.ERRORTYPE</code>.
     */
    public final TableField<AuditstepsRecord, String> ERRORTYPE = createField("ERRORTYPE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.LOGID</code>.
     */
    public final TableField<AuditstepsRecord, String> LOGID = createField("LOGID", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.LOGLEVEL</code>.
     */
    public final TableField<AuditstepsRecord, String> LOGLEVEL = createField("LOGLEVEL", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.LOGTIMESTAMP</code>.
     */
    public final TableField<AuditstepsRecord, String> LOGTIMESTAMP = createField("LOGTIMESTAMP", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.MESSAGE</code>.
     */
    public final TableField<AuditstepsRecord, String> MESSAGE = createField("MESSAGE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.SERVICEPROVIDER</code>.
     */
    public final TableField<AuditstepsRecord, String> SERVICEPROVIDER = createField("SERVICEPROVIDER", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.TRACKINGID</code>.
     */
    public final TableField<AuditstepsRecord, String> TRACKINGID = createField("TRACKINGID", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.UUID</code>.
     */
    public final TableField<AuditstepsRecord, String> UUID = createField("UUID", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.AUDITSTEPS.EAGLEAUDITS_ID</code>.
     */
    public final TableField<AuditstepsRecord, Long> EAGLEAUDITS_ID = createField("EAGLEAUDITS_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>PUBLIC.AUDITSTEPS</code> table reference
     */
    public Auditsteps() {
        this(DSL.name("AUDITSTEPS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.AUDITSTEPS</code> table reference
     */
    public Auditsteps(String alias) {
        this(DSL.name(alias), AUDITSTEPS);
    }

    /**
     * Create an aliased <code>PUBLIC.AUDITSTEPS</code> table reference
     */
    public Auditsteps(Name alias) {
        this(alias, AUDITSTEPS);
    }

    private Auditsteps(Name alias, Table<AuditstepsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Auditsteps(Name alias, Table<AuditstepsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUDITSTEPS_EAGLEAUDITS_FK_INDEX_8, Indexes.PRIMARY_KEY_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuditstepsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuditstepsRecord>> getKeys() {
        return Arrays.<UniqueKey<AuditstepsRecord>>asList(Keys.CONSTRAINT_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AuditstepsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AuditstepsRecord, ?>>asList(Keys.AUDITSTEPS_EAGLEAUDITS_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Auditsteps as(String alias) {
        return new Auditsteps(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Auditsteps as(Name alias) {
        return new Auditsteps(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Auditsteps rename(String name) {
        return new Auditsteps(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auditsteps rename(Name name) {
        return new Auditsteps(name, null);
    }
}
