/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl;


import javax.annotation.Generated;

import org.citi.model.ddl.tables.Auditsteps;
import org.citi.model.ddl.tables.Eagleaudits;
import org.citi.model.ddl.tables.Logstep;
import org.citi.model.ddl.tables.Numtx;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUDITSTEPS_EAGLEAUDITS_FK_INDEX_8 = Indexes0.AUDITSTEPS_EAGLEAUDITS_FK_INDEX_8;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index LOGSTEP_AUDITSTEPS_FK_INDEX_3 = Indexes0.LOGSTEP_AUDITSTEPS_FK_INDEX_3;
    public static final Index PRIMARY_KEY_3 = Indexes0.PRIMARY_KEY_3;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index AUDITSTEPS_EAGLEAUDITS_FK_INDEX_8 = createIndex("AUDITSTEPS_EAGLEAUDITS_FK_INDEX_8", Auditsteps.AUDITSTEPS, new OrderField[] { Auditsteps.AUDITSTEPS.EAGLEAUDITS_ID }, false);
        public static Index PRIMARY_KEY_8 = createIndex("PRIMARY_KEY_8", Auditsteps.AUDITSTEPS, new OrderField[] { Auditsteps.AUDITSTEPS.ID }, true);
        public static Index PRIMARY_KEY_D = createIndex("PRIMARY_KEY_D", Eagleaudits.EAGLEAUDITS, new OrderField[] { Eagleaudits.EAGLEAUDITS.ID }, true);
        public static Index LOGSTEP_AUDITSTEPS_FK_INDEX_3 = createIndex("LOGSTEP_AUDITSTEPS_FK_INDEX_3", Logstep.LOGSTEP, new OrderField[] { Logstep.LOGSTEP.AUDITSTEPS_ID }, false);
        public static Index PRIMARY_KEY_3 = createIndex("PRIMARY_KEY_3", Logstep.LOGSTEP, new OrderField[] { Logstep.LOGSTEP.ID }, true);
        public static Index PRIMARY_KEY_4 = createIndex("PRIMARY_KEY_4", Numtx.NUMTX, new OrderField[] { Numtx.NUMTX.ID }, true);
    }
}
