/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl;


import javax.annotation.Generated;

import org.citi.model.ddl.tables.Auditsteps;
import org.citi.model.ddl.tables.Eagleaudits;
import org.citi.model.ddl.tables.Logstep;
import org.citi.model.ddl.tables.Numtx;
import org.citi.model.ddl.tables.records.AuditstepsRecord;
import org.citi.model.ddl.tables.records.EagleauditsRecord;
import org.citi.model.ddl.tables.records.LogstepRecord;
import org.citi.model.ddl.tables.records.NumtxRecord;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuditstepsRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<EagleauditsRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<LogstepRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<NumtxRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<NumtxRecord> U_NUMTX_ID = UniqueKeys0.U_NUMTX_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuditstepsRecord, EagleauditsRecord> AUDITSTEPS_EAGLEAUDITS_FK = ForeignKeys0.AUDITSTEPS_EAGLEAUDITS_FK;
    public static final ForeignKey<LogstepRecord, AuditstepsRecord> LOGSTEP_AUDITSTEPS_FK = ForeignKeys0.LOGSTEP_AUDITSTEPS_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuditstepsRecord> CONSTRAINT_8 = createUniqueKey(Auditsteps.AUDITSTEPS, "CONSTRAINT_8", Auditsteps.AUDITSTEPS.ID);
        public static final UniqueKey<EagleauditsRecord> CONSTRAINT_D = createUniqueKey(Eagleaudits.EAGLEAUDITS, "CONSTRAINT_D", Eagleaudits.EAGLEAUDITS.ID);
        public static final UniqueKey<LogstepRecord> CONSTRAINT_3 = createUniqueKey(Logstep.LOGSTEP, "CONSTRAINT_3", Logstep.LOGSTEP.ID);
        public static final UniqueKey<NumtxRecord> CONSTRAINT_4 = createUniqueKey(Numtx.NUMTX, "CONSTRAINT_4", Numtx.NUMTX.ID);
        public static final UniqueKey<NumtxRecord> U_NUMTX_ID = createUniqueKey(Numtx.NUMTX, "U_NUMTX_ID", Numtx.NUMTX.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AuditstepsRecord, EagleauditsRecord> AUDITSTEPS_EAGLEAUDITS_FK = createForeignKey(org.citi.model.ddl.Keys.CONSTRAINT_D, Auditsteps.AUDITSTEPS, "AUDITSTEPS_EAGLEAUDITS_FK", Auditsteps.AUDITSTEPS.EAGLEAUDITS_ID);
        public static final ForeignKey<LogstepRecord, AuditstepsRecord> LOGSTEP_AUDITSTEPS_FK = createForeignKey(org.citi.model.ddl.Keys.CONSTRAINT_8, Logstep.LOGSTEP, "LOGSTEP_AUDITSTEPS_FK", Logstep.LOGSTEP.AUDITSTEPS_ID);
    }
}
