/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.Generated;

import org.citi.model.ddl.tables.Auditsteps;
import org.citi.model.ddl.tables.Eagleaudits;
import org.citi.model.ddl.tables.Logstep;
import org.citi.model.ddl.tables.Numtx;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.2" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -933113760;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * The table <code>PUBLIC.AUDITSTEPS</code>.
	 */
	public final Auditsteps AUDITSTEPS = org.citi.model.ddl.tables.Auditsteps.AUDITSTEPS;

	/**
	 * The table <code>PUBLIC.EAGLEAUDITS</code>.
	 */
	public final Eagleaudits EAGLEAUDITS = org.citi.model.ddl.tables.Eagleaudits.EAGLEAUDITS;

	/**
	 * The table <code>PUBLIC.LOGSTEP</code>.
	 */
	public final Logstep LOGSTEP = org.citi.model.ddl.tables.Logstep.LOGSTEP;

	/**
	 * The table <code>PUBLIC.NUMTX</code>.
	 */
	public final Numtx NUMTX = org.citi.model.ddl.tables.Numtx.NUMTX;

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC", null);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(Eagleaudits.EAGLEAUDITS, Auditsteps.AUDITSTEPS, Logstep.LOGSTEP, Numtx.NUMTX);
	}

	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private Collection getSequences0() {
		return Arrays.<Sequence<?>>asList(Sequences.SYSTEM_SEQUENCE_205A61F8_CFCE_4731_82B5_D948F6362318,
				Sequences.SYSTEM_SEQUENCE_20CBB021_ACCB_4660_896C_AD7B857F82CD,
				Sequences.SYSTEM_SEQUENCE_62ADF8A1_25C6_4569_82AB_45BDF920DA2A,
				Sequences.SYSTEM_SEQUENCE_7FF407BD_96F3_44C6_99C1_094D9C5B01A1);
	}
}
