/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_205A61F8_CFCE_4731_82B5_D948F6362318</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_205A61F8_CFCE_4731_82B5_D948F6362318 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_205A61F8_CFCE_4731_82B5_D948F6362318", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_20CBB021_ACCB_4660_896C_AD7B857F82CD</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_20CBB021_ACCB_4660_896C_AD7B857F82CD = new SequenceImpl<Long>("SYSTEM_SEQUENCE_20CBB021_ACCB_4660_896C_AD7B857F82CD", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_62ADF8A1_25C6_4569_82AB_45BDF920DA2A</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_62ADF8A1_25C6_4569_82AB_45BDF920DA2A = new SequenceImpl<Long>("SYSTEM_SEQUENCE_62ADF8A1_25C6_4569_82AB_45BDF920DA2A", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_7FF407BD_96F3_44C6_99C1_094D9C5B01A1</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_7FF407BD_96F3_44C6_99C1_094D9C5B01A1 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_7FF407BD_96F3_44C6_99C1_094D9C5B01A1", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
