/*
 * This file is generated by jOOQ.
*/
package org.citi.model.ddl;


import javax.annotation.Generated;

import org.citi.model.ddl.tables.Auditsteps;
import org.citi.model.ddl.tables.Eagleaudits;
import org.citi.model.ddl.tables.Logstep;
import org.citi.model.ddl.tables.Numtx;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUDITSTEPS</code>.
     */
    public static final Auditsteps AUDITSTEPS = org.citi.model.ddl.tables.Auditsteps.AUDITSTEPS;

    /**
     * The table <code>PUBLIC.EAGLEAUDITS</code>.
     */
    public static final Eagleaudits EAGLEAUDITS = org.citi.model.ddl.tables.Eagleaudits.EAGLEAUDITS;

    /**
     * The table <code>PUBLIC.LOGSTEP</code>.
     */
    public static final Logstep LOGSTEP = org.citi.model.ddl.tables.Logstep.LOGSTEP;

    /**
     * The table <code>PUBLIC.NUMTX</code>.
     */
    public static final Numtx NUMTX = org.citi.model.ddl.tables.Numtx.NUMTX;
}
